name: weather_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash_image.png"
  branding: "assets/images/brand_image.png"
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/